version: '3'
services:
  dbpostgres:
    image: postgres:12-alpine
    container_name: mypostgres
    #env_file: ./postgres.env
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=Initial0
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nomination

  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - 8000:80
    links:
      - dbpostgres:dbpostgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sap.com
      - PGADMIN_DEFAULT_PASSWORD=Initial0